# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IESDP
email: your-email@domain.com
description: >
  The IESDP (Infinity Engine Structures Description Project) is an effort
  to research the workings of the Bioware Infinity Engine(R), and act as a
  collective resource for those interested in such workings.
baseurl: "/iesdp" # the subpath of your site, e.g. /blog
url: "https://lynxlynxlynx.github.io"
github_url:  "https://github.com/lynxlynxlynx/iesdp/"
github_archive:  "https://github.com/lynxlynxlynx/iesdp/archive/gh-pages.zip"
g3_forum: "http://gibberlings3.net/forums/index.php?showforum=54"

# Build settings
markdown: kramdown

sass:
  style: :nested

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

exclude: [vendor]
