name: Updater

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # ensure the zip archive has proper links ... so manually trigger the build after some prep
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5

    - name: Install dependencies & build site
      uses: limjh16/jekyll-action-ts@v2
      #with:
        #enable_cache: true

    - name: Push to other branch for a clean build
      run: bash deploy.sh
